options:
  merge-default-rules: true
#  formatter: html
#  output-file: 'sass-lint.html'

rules:
  border-zero: 0
  class-name-format: 0
  clean-import-paths: 0
  empty-line-between-blocks: 0
  final-newline: 0
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  hex-length: 0
  indentation: 0
  leading-zero: 0
  mixin-name-format: 0
  nesting-depth: 0
  no-color-literals: 0
  no-css-comments: 0
  no-empty-args: 0
  no-empty-rulesets: 0
  no-ids: 0
  no-important: 0
  no-mergeable-selectors: 0
  no-qualifying-elements: 0
  no-url-protocols: 0
  no-vendor-prefixes: 0
  one-declaration-per-line: 0
  placeholder-in-extend: 0
  property-sort-order: 0
  quotes: 0
  shorthand-values: 0
  single-line-per-selector: 0
  space-after-colon: 0
  space-after-comma: 0
  space-around-operator: 0
  space-before-brace: 0
  space-between-parens: 0
  variable-name-format: 0
  zero-unit: 0
  url-quotes: 0
  no-transition-all: 0
  brace-style: 0

  no-color-keywords: 1
  hex-notation: 1
  mixins-before-declarations: 1
  trailing-semicolon: 1
  no-duplicate-properties: 2

#rules:
#  quotes: 0
#  final-newline: 0
#  extends-before-mixins: 2
#  extends-before-declarations: 2
#  placeholders-in-extend: 2
#  mixins-before-declarations:
#    - 2
#    -
#      exclude:
#        - breakpoint
#        - mq
#
#  no-warn: 1
#  no-debug: 1
#  no-ids: 2
#  no-important: 2
#  hex-notation:
#    - 2
#    -
#      style: uppercase
#  indentation:
#    - 2
#    -
#      size: 2
#  variable-for-property:
#    - 2
#    -
#      properties:
#        - margin
#        - content